//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bigview.Bot.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bigview.Bot.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disculpa, aún no puedo responder a esa solicitud. Sin embargo puedo orientarte en los siguientes servicios:.
        /// </summary>
        internal static string AnswerQuestionHandlerAsyncNotUnderstand {
            get {
                return ResourceManager.GetString("AnswerQuestionHandlerAsyncNotUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disculpa, aún no puedo responder a esa solicitud. Sin embargo puedo orientarte en los siguientes servicios:.
        /// </summary>
        internal static string BotNotUnderstand {
            get {
                return ResourceManager.GetString("BotNotUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelando ....
        /// </summary>
        internal static string CancelAndHelpDialogCancelMsgText {
            get {
                return ResourceManager.GetString("CancelAndHelpDialogCancelMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monstrando la ayuda que se requiere para el funcionamiento del BOT.
        /// </summary>
        internal static string CancelAndHelpDialogHelpMsgText {
            get {
                return ResourceManager.GetString("CancelAndHelpDialogHelpMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstCard.json.
        /// </summary>
        internal static string CardsFirtsCard {
            get {
                return ResourceManager.GetString("CardsFirtsCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuCard.json.
        /// </summary>
        internal static string CardsPrincipalMenu {
            get {
                return ResourceManager.GetString("CardsPrincipalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secondCard.json.
        /// </summary>
        internal static string CardsSecondCard {
            get {
                return ResourceManager.GetString("CardsSecondCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcomeCard.json.
        /// </summary>
        internal static string CardsWelcomeCard {
            get {
                return ResourceManager.GetString("CardsWelcomeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parece que aun no estoy entrenado para responderte esto.
        /// </summary>
        internal static string ConversationalHandlerAsyncNotUnderstand {
            get {
                return ResourceManager.GetString("ConversationalHandlerAsyncNotUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calificaciones.
        /// </summary>
        internal static string DialogsEntityCalificaciones {
            get {
                return ResourceManager.GetString("DialogsEntityCalificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to certificaciones.
        /// </summary>
        internal static string DialogsEntityCertificaciones {
            get {
                return ResourceManager.GetString("DialogsEntityCertificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running dialog with Message Activity..
        /// </summary>
        internal static string LoggerOnMessageActivityAsync {
            get {
                return ResourceManager.GetString("LoggerOnMessageActivityAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola  {0}, Sú nota final encontrada en nuestros servicios {1}..
        /// </summary>
        internal static string MenuDialogStudentFount {
            get {
                return ResourceManager.GetString("MenuDialogStudentFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogState.
        /// </summary>
        internal static string PropertyDialogState {
            get {
                return ResourceManager.GetString("PropertyDialogState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estudiante no ha sido encontrado.
        /// </summary>
        internal static string StudentServiceAdapterNotFound {
            get {
                return ResourceManager.GetString("StudentServiceAdapterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un gusto haberte logrado apoyar. Estoy para lo que necesites.
        /// </summary>
        internal static string TranscriptDialogEndMessage {
            get {
                return ResourceManager.GetString("TranscriptDialogEndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indícame tu ID UNIMINUTO para continuar:
        ///
        ///En el caso de tener 6 dígitos, debes anteponer 3 ceros (000). En el caso de tener 5 dígitos, debes anteponer 4 ceros (0000).
        /// </summary>
        internal static string TranscriptDialogInitialMessage {
            get {
                return ResourceManager.GetString("TranscriptDialogInitialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código suministrado de estudiante no es valido.
        /// </summary>
        internal static string TranscriptDialogInvalidCode {
            get {
                return ResourceManager.GetString("TranscriptDialogInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido al Bot BIU.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
